### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by dineshreddy221** [databricks-industry-solutions/merchant-classification#6]
When i am running this accelerator in databricks, path doesn't exists, Do we need to change the path or how to get that dataset.

**Comment by aamend** [comment]
> When i am running this accelerator in databricks, path doesn't exists, Do we need to change the path or how to get that dataset.
> 
> 
> 
> 

Thanks for your interest in this solution. This specific dataset is not public, we cannot share. Goal of our solution is really to accelerate value using your own enterprise data

**Comment by dineshreddy221** [comment]
Thanks for your response.
